=== Propato/Tonto/packages/tonto/tonto-manifest-schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "description": "An manifest object to determine a Tonto project configuration",
  "properties": {
    "projectName": {
      "type": "string",
      "description": "The name of the project without spaces or special characters"
    },
    "version": {
      "type": "string",
      "description": "Version of the project in the format of x.x.x"
    },
    "displayName": {
      "type": "string",
      "description": "The name of the project that will be displayed on the Project variable"
    },
    "license": {
      "type": "string",
      "description": "The license of the project"
    },
    "publisher": {
      "type": "string",
      "description": "The publisher of the project"
    },
    "authors": {
      "type": "array",
      "additionalProperties": {
        "name": {
          "type": "string"
        },
        "email": {
          "type": "string",
          "format": "email"
        },
        "website": {
          "type": "string",
          "format": "uri"
        }
      }
    },
    "dependencies": {
      "type": "object",
      "additionalProperties": {
        "type": "object",
        "properties": {
          "url": {
            "type": "string",
            "format": "uri"
          },
          "version": {
            "type": "string"
          },
          "directory": {
            "type": "string"
          }
        },
        "required": [
          "url",
          "version"
        ]
      }
    },
    "outFolder": {
      "type": "string"
    }
  },
  "required": [
    "projectName",
    "version",
    "displayName",
    "license",
    "publisher",
    "dependencies",
    "outFolder"
  ]
}

=== Propato/Tonto/examples/ontouml-models/Aguiar2019ooco/tonto.json
{
  "projectName": "Aguiar2019ooco",
  "displayName": "Aguiar 2019 Object Oriented Example",
  "publisher": "Aguiar",
  "version": "1.0.0",
  "license": "MIT",
  "dependencies": {
    "SWO": {
      "url": "https://github.com/SWO",
      "version": "1.0.0"
    },
    "SPO": {
      "url": "https://github.com/SPO",
      "version": "1.0.0"
    }
  },
  "outFolder": "out"
}
